format = """$username$directory$python$git_branch$git_status
$cmd_duration$character"""

[character]
success_symbol = "[ |](bold green)"
error_symbol = "[ |](bold red)"
vicmd_symbol = "[V](bold green)"

[directory]
fish_style_pwd_dir_length = 1
repo_root_style = "bold cyan underline"
truncate_to_repo = false

[python]
symbol="󰌠 "

[cmd_duration]
min_time = 1000

[username]
disabled = false
show_always = true
style_user = "bold fg:#bd93f9"

[git_branch]
symbol=" "
